#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="cups"

check_container_initialized
check_service_initialized 10-cupsd
liftoff

print_start "Starting cups"
exec /usr/sbin/cupsd -f
#CMD ["/usr/sbin/cupsd", "-f"]