#!/bin/bash
rpcclient localhost -U root%yourpassword <<EOF
adddriver "Windows x64" "Kyocera3501i:OEMSETUP.INF:kyocera.dll:kyoceraui.dll:kyocerasetup.dll"
adddriver "Windows x64" "KonicaC250i:OEMSETUP.INF:kmmon.dll:kmsetup.dll:kmui.dll"
EOF