#!/command/with-contenv bash

source /assets/functions/00-container
# prepare_service defaults 10-cupsd
PROCESS_NAME="dbus-daemon"

check_container_initialized
# check_service_initialized init
liftoff

print_start "Starting avahi-daemon"
exec /usr/bin/dbus-daemon --system --nofork
#CMD ["/usr/sbin/avahi-daemon", "--daemonize"]

#exec s6-setuidgid root /usr/sbin/cupsd -f
