#!/command/with-contenv bash

source /assets/functions/00-container
# prepare_service defaults 10-cupsd
PROCESS_NAME="rpcclient-init"

check_container_initialized
# check_service_initialized init
liftoff

print_start "Running rpcclient-init once"

bash -c 'rpcclient localhost -U root%yourpassword <<EOF
adddriver "Windows x64" "Kyocera3501i:OEMSETUP.INF:kyocera.dll:kyoceraui.dll:kyocerasetup.dll"
adddriver "Windows x64" "KonicaC250i:OEMSETUP.INF:kmmon.dll:kmsetup.dll:kmui.dll"
EOF
'

#exec s6-setuidgid root /usr/sbin/cupsd -f
